var applicationResources = {
    applicationNameString: "RM",
    homePageString: "Home",
    projectPageString: "Home",
    thingPageString: "Items",
    typePageString: "Item Types",
    connectionPageString: "Connections",
    connectorPageString: "Connection Types",
    visualisePageString: "Visualise (Force)",
    propertiesString: "Properties",
    createdString: "Created",
    updatedString: "Updated",
    createdHelpString: "Date and time created",
    updatedHelpString: "Date and time updated",
    searchPlaceholderString: "Search criteria...",
    searchString: "Search",
    saveString: "Save",
    deleteString: "Delete",
}
