var typeResources = {
    pageTitleString: "Types",
    identifierColumnHeaderString: "Identifier",
    descriptionColumnHeaderString: "Description",
    iconColumnHeaderString: "Icon",
    actionsColumnHeaderString: "Actions",
    deleteButtonString: "Delete",
    viewButtonString: "View",
    createLabelString: "Add new",
    iconHelpString: "The icon displayed when visualising items.",
    identifierHelpString: "The identifier displayed for this item.",
    colourHelpString: "The colour used when displaying items of this type.",
    descriptionHelpString: "A detailed description for this type.",
    modalTitleString: "Properties", 
    visibleColumnHeaderString: "Visible", 
    icons: [
        { name: "address-book", unicode: "f2b9" },
        { name: "address-card", unicode: "f2bb" },
        { name: "angry", unicode: "f556" },
        { name: "arrow-alt-circle-down", unicode: "f358" },
        { name: "arrow-alt-circle-left", unicode: "f359" },
        { name: "arrow-alt-circle-right", unicode: "f35a" },
        { name: "arrow-alt-circle-up", unicode: "f35b" },
        { name: "bell", unicode: "f0f3" },
        { name: "bell-slash", unicode: "f1f6" },
        { name: "bookmark", unicode: "f02e" },
        { name: "building", unicode: "f1ad" },
        { name: "calendar", unicode: "f133" },
        { name: "calendar-alt", unicode: "f073" },
        { name: "calendar-check", unicode: "f274" },
        { name: "calendar-minus", unicode: "f272" },
        { name: "calendar-plus", unicode: "f271" },
        { name: "calendar-times", unicode: "f273" },
        { name: "caret-square-down", unicode: "f150" },
        { name: "caret-square-left", unicode: "f191" },
        { name: "caret-square-right", unicode: "f152" },
        { name: "caret-square-up", unicode: "f151" },
        { name: "chart-bar", unicode: "f080" },
        { name: "check-circle", unicode: "f058" },
        { name: "check-square", unicode: "f14a" },
        { name: "circle", unicode: "f111" },
        { name: "clipboard", unicode: "f328" },
        { name: "clock", unicode: "f017" },
        { name: "clone", unicode: "f24d" },
        { name: "closed-captioning", unicode: "f20a" },
        { name: "comment", unicode: "f075" },
        { name: "comment-alt", unicode: "f27a" },
        { name: "comment-dots", unicode: "f4ad" },
        { name: "comments", unicode: "f086" },
        { name: "compass", unicode: "f14e" },
        { name: "copy", unicode: "f0c5" },
        { name: "copyright", unicode: "f1f9" },
        { name: "credit-card", unicode: "f09d" },
        { name: "dizzy", unicode: "f567" },
        { name: "dot-circle", unicode: "f192" },
        { name: "edit", unicode: "f044" },
        { name: "envelope ", unicode: "f40e0" },
        { name: "envelope-open", unicode: "f2b6" },
        { name: "eye", unicode: "f06e" },
        { name: "eye-slash", unicode: "f070" },
       { name: "file", unicode: "f15b" },
        { name: "file-alt", unicode: "f15c" },
        { name: "file-archive", unicode: "f1c6" },
        { name: "file-audio", unicode: "f1c7" },
        { name: "file-code", unicode: "f1c9" },
        { name: "file-excel ", unicode: "f1c3" },
        { name: "file-image", unicode: "f1c5" },
        { name: "file-pdf", unicode: "f1c1" },
        { name: "file-powerpoint", unicode: "f1c4" },
        { name: "file-video", unicode: "f1c8" },
        { name: "file-word", unicode: "f1c2" },
        { name: "flag", unicode: "f024" },
        { name: "flushed", unicode: "f579" },
        { name: "folder", unicode: "f07b" },
        { name: "folder-open ", unicode: "f07c" },
        { name: "frown", unicode: "f119" },
        { name: "frown-open", unicode: "f57a" },
        { name: "futbol", unicode: "f1e3" },
        { name: "gem", unicode: "f3a5" },
        { name: "grimace", unicode: "f57f" },
        { name: "grin", unicode: "f580" },
        { name: "grin-alt", unicode: "f581" },
        { name: "grin-beam", unicode: "f582" },
        { name: "grin-beam-sweet ", unicode: "f583" },
        { name: "grin-hearts", unicode: "f584" },
        { name: "grin-squint", unicode: "f585" },
        { name: "grin-squint-tears", unicode: "f586" },
        { name: "grin-stars", unicode: "f587" },
        { name: "grin-tears", unicode: "f588" },
        { name: "grin-tongue", unicode: "f589" },
        { name: "grin-tongue-squint", unicode: "f58a" },
        { name: "grin-tongue-wink", unicode: "f58b" },
        { name: "grin-wink ", unicode: "f58c" },
        { name: "hand-lizard", unicode: "f258" },
        { name: "hand-paper", unicode: "f256" },
        { name: "hand-peace", unicode: "f25b" },
        { name: "hand-point-down", unicode: "f0a7" },
        { name: "hand-point-left", unicode: "f0a5" },
        { name: "hand-point-right", unicode: "f0a4" },
        { name: "hand-point-up", unicode: "f0a6" },
        { name: "hand-pointer", unicode: "f25a" },
        { name: "hand-rock ", unicode: "f255" },
        { name: "hand-scissors", unicode: "f257" },
        { name: "hand-spock", unicode: "f259" },
        { name: "handshake", unicode: "f2b5" },
        { name: "hdd", unicode: "f0a0" },
        { name: "heart", unicode: "f004" },
        { name: "home", unicode: "f015" },
        { name: "hospital", unicode: "f0f8" },
        { name: "hourglass", unicode: "f254" },
        { name: "id-badge", unicode: "f2c1" },
        { name: "id-card ", unicode: "f2c2" },
        { name: "image", unicode: "f03e" },
        { name: "images", unicode: "f302" },
       { name: "keyboard", unicode: "f11c" },
        { name: "kiss", unicode: "f596" },
        { name: "kiss-beam", unicode: "f597" },
        { name: "kiss-wink-heart", unicode: "f598" },
        { name: "laugh", unicode: "f599" },
        { name: "laugh-beam", unicode: "f59a" },
        { name: "laugh-squint ", unicode: "f59b" },
        { name: "laugh-wink", unicode: "f59c" },
        { name: "lemon", unicode: "f094" },
        { name: "life-ring", unicode: "f1cd" },
        { name: "lightbulb", unicode: "f0eb" },
        { name: "list-alt", unicode: "f022" },
        { name: "map", unicode: "f279" },
        { name: "meh", unicode: "f11a" },
        { name: "meh-blank", unicode: "f5a4" },
        { name: "meh-rolling-eyes ", unicode: "f5a5" },
        { name: "minus-square", unicode: "f146" },
        { name: "money-bill-alt", unicode: "f3d1" },
        { name: "moon", unicode: "f186" },
        { name: "newspaper", unicode: "f1ea" },
        { name: "object-group", unicode: "f247" },
        { name: "object-upgroup", unicode: "f248" },
        { name: "paper-plane", unicode: "f1d8" },
        { name: "pause-circle", unicode: "f28b" },
        { name: "play-circle ", unicode: "f144" },
        { name: "plus-square", unicode: "f0fe" },
        { name: "question-circle", unicode: "f059" },
        { name: "registered", unicode: "f25d" },
        { name: "sad-cry", unicode: "f5b3" },
        { name: "sad-tear", unicode: "f5b4" },
        { name: "save", unicode: "f0c7" },
        { name: "share-square", unicode: "f14d" },
        { name: "smile", unicode: "f118" },
        { name: "smile-beam ", unicode: "f5b8" },
        { name: "smile-wink", unicode: "f4da" },
        { name: "snowflake", unicode: "f2dc" },
        { name: "square", unicode: "f0c8" },
        { name: "star", unicode: "f005" },
        { name: "star-half", unicode: "f089" },
        { name: "sticky-note", unicode: "f249" },
        { name: "stop-circle", unicode: "f28d" },
       { name: "sun", unicode: "f185" },
        { name: "surprise ", unicode: "f5c2" },
        { name: "thumbs-down", unicode: "f165" },
        { name: " thumbs-up", unicode: "f1164" },
        { name: "times-circle", unicode: "f057" },
        { name: "tired", unicode: "f5c8" },
        { name: "trash-alt", unicode: "f2ed" },
        { name: "user", unicode: "f007" },
        { name: "user-circle", unicode: "f2bd" },
        { name: "window-close", unicode: "f410" },
        { name: "window-maximize ", unicode: "f2d0" },
        { name: "window-minimize", unicode: "f2d1" },
        { name: "window-restore", unicode: "f2d2" },
    ]
}
