var connectionResources = {
    pageTitleString: "Connection",
    identifierColumnHeaderString: "Identifier",
    descriptionColumnHeaderString: "Description",
    sourceColumnHeaderString: "Source",
    targetColumnHeaderString: "Target",
    connectorColumnHeaderString: "Connector",
    actionsColumnHeaderString: "Actions",
    deleteButtonString: "Delete",
    viewButtonString: "View",
    createLabelString: "Add new",
    identifierHelpString: "The identifier displayed for this item.",
    colourHelpString: "The colour used when displaying this Connection.",
    descriptionHelpString: "A detailed description for this Connection.",
    modalTitleString: "Properties", 
    updatedColumnHeaderString: "Updated", 
}
